# Generated by Django 6.1.1 on 2026-09-15 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('league', models.CharField(max_length=100)),
                ('stadium', models.CharField(max_length=150)),
                ('founded', models.IntegerField()),
                ('trophies', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('colors', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('country', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('Club', 'Club'), ('National', 'National')], max_length=20)),
                ('founded', models.IntegerField()),
                ('teams', models.IntegerField()),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('position', models.CharField(choices=[('Goalkeeper', 'Goalkeeper'), ('Defender', 'Defender'), ('Midfielder', 'Midfielder'), ('Forward', 'Forward')], max_length=20)),
                ('shirt_number', models.IntegerField(default=0)),
                ('appearances', models.IntegerField(default=0)),
                ('goals', models.IntegerField(default=0)),
                ('assists', models.IntegerField(default=0)),
                ('trophies', models.IntegerField(default=0)),
                ('image', models.URLField(blank=True)),
                ('club', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='players', to='football.club')),
            ],
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_club', models.CharField(max_length=100)),
                ('to_club', models.CharField(max_length=100)),
                ('season', models.CharField(max_length=20)),
                ('fee', models.CharField(max_length=50)),
                ('transfer_type', models.CharField(choices=[('Transfer', 'Transfer'), ('Return', 'Return'), ('Loan', 'Loan')], max_length=20)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='football.player')),
            ],
        ),
    ]
