# Generated by Django 6.1.1 on 2026-09-15 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0002_timelineevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(choices=[('GK', 'Goalkeeper'), ('LB', 'Left Back'), ('CB', 'Center Back'), ('RB', 'Right Back'), ('LWB', 'Left Wing Back'), ('RWB', 'Right Wing Back'), ('CDM', 'Defensive Midfielder'), ('CM', 'Central Midfielder'), ('CAM', 'Attacking Midfielder'), ('LM', 'Left Midfielder'), ('RM', 'Right Midfielder'), ('LW', 'Left Winger'), ('RW', 'Right Winger'), ('ST', 'Striker'), ('CF', 'Center Forward')], max_length=5),
        ),
    ]
